name: WorldUtilities
main: util.PluginCore
version: 1.0
api-version: 1.17
commands:
 switch: 
  description: Switch to existing world
  usage: "/<command> <world-name>"

 create:
  description: Create a world
  usage: "/<command> <world-name>"
  permission: op

 backup:
  description: Backup a world
  usage: "/<command>"
  permission: op
 
 delete:
  description: Delete a world permanently
  usage: "/<command> <world-name>"
  permission: op

 current:
  description: Name of current world
  usage: "/<command>"