name: ServerArbiterPower
version: '${project.version}'
main: com.xessmcserver.serverarbiterpower.ServerArbiterPower
api-version: 1.18
authors: [ XessWaffle ]
description: Server Arbiter Powers (includes trolling functionality)
website: xesswaffle.github.io
commands:
  enforce:
    description: Enforce a decree upon a player
    usage: "/<command> <player> <decree> <probability>"
    permission: op

  enforced:
    description: List all targets
    usage: "/<command>"
    permission: op

  unenforce:
    description: Remove all decrees targeting a player
    usage: "/<command> <player> <decree>"
    permission: op
